### ISSUE TITLE
Verify X-Hub-Signature if present

### ISSUE THREAD

**Issue by tsibley** [nichtich/Plack-App-GitHub-WebHook#7]
This needs the shared secret for the hook passed into the constructor.  With the secret + request body data + Digest::HMAC, requests which don't match the signature can be rejected.

https://developer.github.com/webhooks/#delivery-headers
https://developer.github.com/v3/repos/hooks/#example
https://metacpan.org/pod/Digest::HMAC

**Comment by nichtich** [comment]
Thanks to @Songmu there is [Plack::Middleware::HubSignature](https://metacpan.org/pod/Plack::Middleware::HubSignature). I'll add a `secret` option to enable this middleware.

**Comment by Songmu** [comment]
:+1:

**Comment by nichtich** [comment]
parameter `secret` will be supported in version 0.8 (not on CPAN yet)
